# Generated by Django 3.0.7 on 2020-06-12 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=300)),
                ('user_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Users Email List',
                'verbose_name_plural': 'Users Email List',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'Enter unique title.'}, max_length=2000, unique=True, verbose_name='Post Title')),
                ('post_description', models.TextField(blank=True, null=True)),
                ('overview', models.TextField(default='Default short des.')),
                ('post_images', models.ImageField(blank=True, upload_to='pics')),
                ('date_of_publish', models.DateField(default=django.utils.timezone.now)),
                ('published', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default=None, max_length=250)),
                ('featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Author')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
            },
        ),
    ]
