# Generated by Django 3.0.7 on 2020-06-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200612_1951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailList',
        ),
    ]
