# Generated by Django 3.0.7 on 2020-06-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200612_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='pics')),
                ('banner_Heading', models.CharField(max_length=1000)),
                ('banner_description', models.TextField()),
            ],
        ),
    ]
