# Generated by Django 3.0.7 on 2020-06-13 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_homebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='featured',
            field=models.BooleanField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='banner_Heading',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
