# Generated by Django 3.0.7 on 2020-06-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200613_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='banner_Heading',
            field=models.CharField(max_length=1000),
        ),
    ]
