# Generated by Django 3.0.7 on 2020-06-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200613_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='youtube',
            field=models.BooleanField(default=False),
        ),
    ]
