# Generated by Django 3.0.7 on 2020-06-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_queries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queries',
            old_name='status',
            new_name='solved_status',
        ),
    ]
