# Generated by Django 3.0.7 on 2020-06-14 11:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200613_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='overview',
            field=tinymce.models.HTMLField(),
        ),
    ]
