# Generated by Django 3.0.7 on 2020-06-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=300)),
                ('user_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Users Email List',
                'verbose_name_plural': 'Users Email List',
            },
        ),
    ]
